"""added interview mode field

Revision ID: 936267d41a66
Revises: f63cabb527bd
Create Date: 2026-04-03 21:14:20.687793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936267d41a66'
down_revision = 'f63cabb527bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('reminder_email')

    # ### end Alembic commands ###
