"""added interview mode field

Revision ID: f63cabb527bd
Revises: 
Create Date: 2026-03-31 23:34:29.424176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63cabb527bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_letter_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('offer_letter_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_column('offer_letter_message')
        batch_op.drop_column('offer_letter_path')

    # ### end Alembic commands ###
